version: '3'
services:
  postgresql:
    image: postgres
    restart: unless-stopped
    env_file:
      - .env/postgresql-postgres.env
      - .env/postgresql.env
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./setup-postgresql.sh:/docker-entrypoint-initdb.d/setup-postgresql.sh
      - ./.env/pg-server.crt:/var/lib/postgresql/server.crt
      - ./.env/pg-server.key:/var/lib/postgresql/server.key
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
  databunker-init:
    #build: .
    image: securitybunker/databunker:latest
    env_file:
      - .env/databunker.env
      - .env/databunker-root.env
    depends_on:
      - postgresql
    entrypoint: /bin/sh
    command: -c "/bin/busybox sleep 3; /databunker/bin/databunker -init -db databunkerdb"
  databunker:
    #build: .
    image: securitybunker/databunker:latest
    restart: unless-stopped
    env_file:
      - .env/databunker.env
    entrypoint: /bin/sh
    command: -c "/databunker/bin/databunker -start -db databunkerdb -conf /databunker/conf/databunker.yaml"
    depends_on:
      - postgresql
    ports:
      - 3000:3000
